def sendMessage(user):
    def setBody(body):
        print(f'Dear {user}, this message was generated by Step It. {body}')
    return setBody


sendMessageToAslan = sendMessage("Aslan")
sendMessageToAslan("Hi aslan")
sendMessageToAslan("Now I will send the messages only to you")
sendMessageToAslan("Hope you are happy with that")

sendMessage("Another chuvak")("Hi")